{{- if eq .Values.env "prod" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: '123456789'
  APP_DB_USERNAME: 'xxxxx'
  APP_DB_PASSWORD: 'yyyy'
  {{- end }}

  {{- if eq .Values.env "stg" }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_SECRET: '123456789'
  APP_DB_USERNAME: 'xxxxx'
  APP_DB_PASSWORD: 'yyyy'

  {{- if .Values.ingress.enableAuth }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-basic-auth
type: Opaque
data:
  auth: aXRrOiRhcHIxJGpWZ1ExRm12JHkzRmtlRTdxSC5FeHFxc0RYVlg0OC8K
  {{- end }}
  {{- end }}
